{{- if .Values.exporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.exporter.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.exporter.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.exporter.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.exporter.name }}
    spec:
      containers:
        - name: locust-exporter
          image: "containersol/locust_exporter:v0.5.2"
          args:
            # El exportador apunta al servicio del máster de Locust
            - --locust.uri=http://locust:8089
          ports:
            - name: metrics
              containerPort: 9646
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.exporter.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.exporter.name }}
spec:
  selector:
    app: {{ .Values.exporter.name }}
  ports:
    - name: metrics
      port: 9646
      targetPort: 9646
{{- end }}