apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.locustfileConfigMapName }}
  namespace: {{ .Release.Namespace }}
data:
  main.py: |-
{{ .Files.Get (printf "files/%s" .Values.locustfile) | nindent 4 }}